### ISSUE TITLE
LPK Crashes after working with AAD integrated K8s

### ISSUE THREAD

**Issue by irperez** [microsoft/mindaro#54] opened 2020-10-16 15:37 UTC
**Describe the bug**
Recently we got K8s integrated with AAD authentication with our organization, which does utilize two-factor authentication.  We followed the work around instructions to get by and at first this worked just fine.  However the next day I'm seeing a vague error now.  "The process has exited."
![image](https://user-images.githubusercontent.com/1376080/96277709-a0b0ec00-0fa2-11eb-8204-fed3f30d6ad2.png)

I'm able to use kubectl in windows cmd prompt/powershell against the .kubeconfig from Bridge's config.
![image](https://user-images.githubusercontent.com/1376080/96279154-4fa1f780-0fa4-11eb-8415-71bae1d69fd1.png)

This is a big blocker for our team.  At this point I can't debug anything!
 
**To Reproduce**
I setup LPK using normal procedures, except I had to establish the work around for AAD to get by two-factor authentication.  Local kubectl against the LPK .kubeconfig works fine.  I setup LPK config as shown below and clicked the debug button.
![image](https://user-images.githubusercontent.com/1376080/96278011-f7b6c100-0fa2-11eb-9522-08761c0c7cdc.png)

 
**Expected behavior**
Debugging starts
 
**Logs**
Attach logs from the following directory:
For Windows: %TEMP%/Bridge to Kubernetes
[bridge-endpointmanager-2020-10-16-15-25-12-29604.txt](https://github.com/microsoft/mindaro/files/5392648/bridge-endpointmanager-2020-10-16-15-25-12-29604.txt)
[bridge-library-2020-10-16-15-25-11-34228.txt](https://github.com/microsoft/mindaro/files/5392651/bridge-library-2020-10-16-15-25-11-34228.txt)
[bridge-mindarocli-2020-10-16-15-25-10-34228.txt](https://github.com/microsoft/mindaro/files/5392652/bridge-mindarocli-2020-10-16-15-25-10-34228.txt)

For OSX/Linux: $TMPDIR/Bridge to Kubernetes
 
**Environment Details**
Client used (VS Code/Visual Studio):
     VS:      16.7.6
Client's version:  0.1
Operating System: Version	10.0.19041 Build 19041

![image](https://user-images.githubusercontent.com/1376080/96278675-c4286680-0fa3-11eb-8a2e-28b8c93444bf.png)

**Comment by irperez** [comment] 2020-10-16 15:57
After restarting my machine, I was able to proceed.  I'll update if I run into this again.

**Comment by daniv-msft** [comment] 2020-10-16 18:29
Thank you for reporting this issue. Looking at the logs you provided, this is due to an exception in our EndpointManager component:
```
System.Net.Sockets.SocketException: {"ClassName":"System.Net.Sockets.SocketException","Message":"Only one usage of each socket address (protocol/network address/port) is normally permitted."
```

We've seen this once or twice in the past, but investigating it is uneasy as this is transient. If you find any way to reproduce it, please let us know so that we can try to get more data on what might go wrong.

**Comment by irperez** [comment] 2020-10-16 19:28
The only thing I can add that happened was that the previous day I was able to debug just fine.  But then I put my computer to sleep.  The next day after waking the PC up it would not debug.  Rebooting seem to reset the issue.

**Comment by greenie-msft** [comment] 2021-02-11 21:15
Hi @irperez,

I'm closing this thread since there has not been much activity. If you are still experiencing this issue please feel free to reopen. 

Thank you.

**Closed by greenie-msft** 2021-02-11 21:15 UTC
