### ISSUE TITLE
Long Service Names breaks Isolated routing

### ISSUE THREAD

**Issue by JasonWhall** [microsoft/mindaro#78] opened 2020-11-09 15:32 UTC
**Describe the bug**
If you have existing services with names close to the default limit, the cloned service will then exceed this limit causing it to fail.

For example if I have a service named: `my-amazing-service-name-called-service-1-20201109-testing` and then use Bridge to Kubernetes to create a clone service to proxy, bridge to kubernetes extension returns an error
```
Failed to establish a connection. Error: Failed to get routing manager deployment status
```

Looking at the routing manager pod logs deployed into the namespace. It returns a message similar to the below (Redacted real names)
```
{
    "Request": {
        "Method": {
            "Method": "POST"
        },
        "RequestUri": "https://192.168.0.1/api/v1/namespaces/int/services",
        "Properties": {},
        "Content": "{\n  \"metadata\": {\n    \"annotations\": {\n      \"meta.helm.sh/release-name\": \"myReleaseName\",\n      \"meta.helm.sh/release-namespace\": \"myNamespace\"\n    },\n    \"labels\": {\n      \"app.kubernetes.io/managed-by\": \"Helm\",\n      \"chart\": \"myChart\",\n      \"component\": \"myComponent\",\n      \"release\": \"myRelease\",\n      \"routing.visualstudio.io/generated\": \"true\",\n      \"routing.visualstudio.io/triggerEntity\": \"my-ingress.i\"\n    },\n    \"name\": \"my-amazing-service-name-called-service-1-20201109-testing-cloned-routing-svc\",\n    \"namespace\": \"MyNamespace\"\n  },\n  \"spec\": {\n    \"ports\": [\n      {\n        \"name\": \"my-amazing-service-name-called-service-1-20201109-testing\",\n        \"port\": 80,\n        \"protocol\": \"TCP\",\n        \"targetPort\": 8080\n      }\n    ],\n    \"selector\": {\n      \"component\": \"myComponent\"\n    },\n    \"sessionAffinity\": \"None\",\n    \"topologyKeys\": [],\n    \"type\": \"ClusterIP\"\n  }\n}",
        "Headers": {
            "Authorization": [
                "49b25cd303121573"
            ],
            "Content-Type": [
                "application/json; charset=utf-8"
            ],
            "Content-Length": [
                "1040"
            ]
        }
    },
    "Response": {
        "StatusCode": 422,
        "ReasonPhrase": "Unprocessable Entity",
        "Content": "{\"kind\":\"Status\",\"apiVersion\":\"v1\",\"metadata\":{},\"status\":\"Failure\",\"message\":\"Service \\\"my-amazing-service-name-called-service-1-20201109-testing-cloned-routing-svc\\\" is invalid: metadata.name: Invalid value: \\\"my-amazing-service-name-called-service-1-20201109-testing-cloned-routing-svc\\\": must be no more than 63 characters\",\"reason\":\"Invalid\",\"details\":{\"name\":\"my-amazing-service-name-called-service-1-20201109-testing-cloned-routing-svc\",\"kind\":\"Service\",\"causes\":[{\"reason\":\"FieldValueInvalid\",\"message\":\"Invalid value: \\\"my-amazing-service-name-called-service-1-20201109-testing-cloned-routing-svc\\\": must be no more than 63 characters\",\"field\":\"metadata.name\"}]},\"code\":422}\n",
        "Headers": {
            "Audit-Id": [
                "9c010a90-7f8a-48f8-b43f-82e22ecc9da9"
            ],
            "Cache-Control": [
                "no-cache, private"
            ],
            "Date": [
                "Mon, 09 Nov 2020 15:04:25 GMT"
            ],
            "Content-Type": [
                "application/json"
            ],
            "Content-Length": [
                "672"
            ]
        }
    },
    "Body": null,
    "StackTrace": "   at k8s.Kubernetes.CreateNamespacedServiceWithHttpMessagesAsync(V1Service body, String namespaceParameter, String dryRun, String fieldManager, String pretty, Dictionary`2 customHeaders, CancellationToken cancellationToken)\n   at k8s.KubernetesExtensions.CreateNamespacedServiceAsync(IKubernetes operations, V1Service body, String namespaceParameter, String dryRun, String fieldManager, String pretty, CancellationToken cancellationToken)\n   at Microsoft.DevSpaces.RoutingManager.RoutingStateEstablisher.RunAsync(IDictionary`2 inputs, CancellationToken cancellationToken) in /src/routingmanager/RoutingStateEstablisher.cs:line 187\n   at Microsoft.DevSpaces.RoutingManager.RoutingManagerApp.RefreshAsync(CancellationToken cancellationToken) in /src/routingmanager/RoutingManagerApp.cs:line 253\n   at Microsoft.DevSpaces.RoutingManager.RoutingManagerApp.RefreshLoopAsync(CancellationToken cancellationToken) in /src/routingmanager/RoutingManagerApp.cs:line 190",
    "Message": "Operation returned an invalid status code 'UnprocessableEntity'",
    "Data": {},
    "InnerException": null,
    "HelpLink": null,
    "Source": "KubernetesClient",
    "HResult": -2146233088
}
```

This looks to be due to the dns-label limit of 63 characters.

https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#dns-label-names
 
**To Reproduce**
Create 2 deployments with pods in the namespace and have the services close to the character limit (63 chars) and use Bridge to Kubernetes with isolate mode enabled in VS code.

 
**Expected behavior**
Service name is truncated to keep below 63 characters
 
**Environment Details**
Client used (VS Code/Visual Studio): VS Code
 
Client's version: mindaro.mindaro@1.0.120201021
Operating System: Windows 10 1909

**Comment by daniv-msft** [comment] 2020-11-09 21:01
Thanks @JasonWhall for reporting this issue, and sorry you encounter it. This looks like a regression, as we already encountered this issue and fixed it ~2-3 months ago by truncating the service name, as you suggest.

@rakeshvanga Could you please confirm that this looks like the same issue we fixed a couple of months ago?

**Comment by rakeshvanga** [comment] 2020-11-13 02:03
@daniv-msft This looks like the same issue we have fixed but the routing manager is setting up the deployment name differently and needs to be fixed.

@JasonWhall Thanks for reporting the issue. We will get this fixed in the next release.

**Comment by greenie-msft** [comment] 2021-02-05 22:47
We have released a fix for this issue. Closing this thread, but please comment if you are still experiencing this behavior. 

Thank you.

**Closed by greenie-msft** 2021-02-05 22:47 UTC
