### ISSUE TITLE
Generic version of bridge-quickstart.sh?

### ISSUE THREAD

**Issue by wely** [microsoft/mindaro#75] opened 2020-11-04 09:02 UTC
Hi folks,

According to the doc https://docs.microsoft.com/en-us/visualstudio/containers/bridge-to-kubernetes?view=vs-2019, bridge-quickstart.sh needs to be executed during the configuration.

When i browse the file https://github.com/microsoft/mindaro/blob/master/bridge-quickstart.sh, it seems like tightly coupled with the sample app (bikesharingapp).

Question, what should we do if we'd like to enable Bridge-to-Kubernetes to our own app (not the example bikesharingapp)?

I bet we won't be able to use the same bridge-quickstart.sh?

Or perhaps, could you provide guidance / doc in term of what needs to be changed / updated?

**Comment by wely** [comment] 2020-11-04 13:46
Or another way to ask this question is:
What are the steps to use Bridge to Kubernetes on an existing project?

**Comment by amsoedal** [comment] 2020-11-04 17:45
Hi @wely, thanks for your question!
The bridge-quickstart.sh script is indeed only intended for deploying the Bikesharing sample app.  Bridge can be used on your own custom application, but you would need to have it already deployed to your cluster by some other means.  Then you can follow the docs picking up from this section: https://docs.microsoft.com/en-us/visualstudio/containers/bridge-to-kubernetes?view=vs-2019#connect-to-your-cluster-and-debug-a-service

**Comment by wely** [comment] 2020-11-05 02:19
@amsoedal , thanks for getting back to me.

Just to verify about [link you sent me](https://docs.microsoft.com/en-us/visualstudio/containers/bridge-to-kubernetes?view=vs-2019#connect-to-your-cluster-and-debug-a-service), do we still need to execute the bridge-quickstart.sh or can we just ignore it?
![image](https://user-images.githubusercontent.com/1658657/98188584-37dbe480-1f4e-11eb-9783-1a86d8006a5f.png)

I was trying to use Bridge to connect to the Basket API from the [eShopOnContainers](https://github.com/dotnet-architecture/eShopOnContainers).

So, i tried it without running the bridge-quickstart.sh, but directly start the Bridge from VS2019. I notice several issues:

1. No option for me to choose the Ingress (unlike the example shown in Bike App)
![image](https://user-images.githubusercontent.com/1658657/98188901-d8320900-1f4e-11eb-8f90-0c50d1f736c8.png)

2. When i run it, apparently it doesn't work as expected. Nothing happened, though i have put the breakpoint on the code to run.

3. In fact, the service turns unhealthy:
![image](https://user-images.githubusercontent.com/1658657/98189469-0106ce00-1f50-11eb-8236-7ce8ac7666b6.png)
And the error logs indicated that it's unable to reach the api.
![image](https://user-images.githubusercontent.com/1658657/98189554-2bf12200-1f50-11eb-903c-7ae3bca9e8e1.png)

@amsoedal , can the Bridge team create a document / provide more detail and clear guidance in term of setting up Bridge for an existing project?

**Comment by daniv-msft** [comment] 2020-11-05 02:39
Thanks for following up @wely. I confirm you do not need to run bridge-quickstart.sh.
This script is only used to deploy our sample application. As you want to use your own application, you don't need to run this script for your cluster.

Regarding the errors that you see:
- Could you please confirm that you have some Ingress available in your application? This is not a requirement for Bridge to Kubernetes, but you will only see some data in the `Launch browser to` field if you have some.
- Could you please reproduce the issue you're seeing, and then share with us the logs contained in `%TEMP%/Bridge to Kubernetes` and in `%TEMP%\Microsoft.VisualStudio.Kubernetes.Debugging`?
These logs might contain personal data, so feel free to send them by email to `daniv@microsoft.com` if you feel more comfortable with it.

**Comment by wely** [comment] 2020-11-05 03:04
thanks @daniv-msft , sent you an email.

**Comment by xclw2000** [comment] 2020-12-25 01:33
I have the same problem. Do you have a step by step tour for a new project or my own project which use third or a local kubernetes cluster?

**Comment by daniv-msft** [comment] 2020-12-28 17:54
@xclw2000 Thank you for your comment. If you are using VS Code, please have a look at this tutorial: https://code.visualstudio.com/docs/containers/minikube
This tutorial is initially for Minikube, but it can apply to any third-party Kubernetes cluster (if you're not using Minikube, please skip to `Deploy the application`).

If you're using Visual Studio, unfortunately we don't have a tutorial as of today but we're working on it.
Please don't hesitate to try Bridge to Kubernetes on your own project and let us know if we can help you with any issue.

**Comment by greenie-msft** [comment] 2021-02-05 19:49
Closing this issue as we now support a generic QuickStart which can be applied to existing customer applications:

https://code.visualstudio.com/docs/containers/bridge-to-kubernetes

**Closed by greenie-msft** 2021-02-05 19:49 UTC
